headers:
  - for: /**.html
    values:
      Cache-Control: max-age=0, must-revalidate, public
      Referrer-Policy: strict-origin-when-cross-origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
      Accept-Encoding: gzip, compress, br