baseURL: https://upvado.com/
enableRobotsTXT: true

caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: -1
  images:
    dir: :resourceDir/_gen
    maxAge: -1

minify:
  minifyOutput: true

build:
  useResourceCacheWhen: fallback
  writeStats: true
